# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/add_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_database(object):
    def setupUi(self, Add_database):
        Add_database.setObjectName("Add_database")
        Add_database.resize(641, 620)
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(18)
        Add_database.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Add_database)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, -10, 611, 231))
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 220, 561, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(160, 280, 71, 71))
        self.ok_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_button.setStyleSheet("border-radius: 50px;")
        self.ok_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/ok_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok_button.setIcon(icon)
        self.ok_button.setIconSize(QtCore.QSize(70, 70))
        self.ok_button.setFlat(True)
        self.ok_button.setObjectName("ok_button")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 280, 71, 71))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 50px;")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(70, 70))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 410, 161, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        Add_database.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Add_database)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 23))
        self.menubar.setObjectName("menubar")
        Add_database.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Add_database)
        self.statusbar.setObjectName("statusbar")
        Add_database.setStatusBar(self.statusbar)

        self.retranslateUi(Add_database)
        QtCore.QMetaObject.connectSlotsByName(Add_database)

    def retranslateUi(self, Add_database):
        _translate = QtCore.QCoreApplication.translate
        Add_database.setWindowTitle(_translate("Add_database", "Добавление данных"))
        self.label.setText(_translate("Add_database", "Укажите пожалуйста блюдо, которое вы хотите добавить в виде "
                                                      "категория блюда (завтрак, обед...) и название блюда через "
                                                      "пробел"))
        self.lineEdit.setText(_translate("Add_database", "Впишите сюда..."))
        self.ok_button.setToolTip(_translate("Add_database", "Ок"))
        self.pushButton.setToolTip(_translate("Add_database", "Выход"))
