# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/add_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Add_database(object):
    def setupUi(self, Add_database):
        Add_database.setObjectName("Add_database")
        Add_database.resize(641, 620)
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(18)
        Add_database.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Add_database)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 310, 591, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Apple Symbols")
        font.setPointSize(18)
        self.add_button.setFont(font)
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        self.exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Apple Symbols")
        font.setPointSize(18)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, -10, 611, 231))
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 220, 561, 22))
        self.lineEdit.setObjectName("lineEdit")
        Add_database.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Add_database)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 23))
        self.menubar.setObjectName("menubar")
        Add_database.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Add_database)
        self.statusbar.setObjectName("statusbar")
        Add_database.setStatusBar(self.statusbar)

        self.retranslateUi(Add_database)
        QtCore.QMetaObject.connectSlotsByName(Add_database)

    def retranslateUi(self, Add_database):
        _translate = QtCore.QCoreApplication.translate
        Add_database.setWindowTitle(_translate("Add_database", "Добавление данных"))
        self.add_button.setText(_translate("Add_database", "Добавить данные"))
        self.exit_button.setText(_translate("Add_database", "Выйти"))
        self.label.setText(_translate("Add_database", "Укажите пожалуйста блюдо, которое вы хотите добавить в виде категория блюда (завтрак, обед...) и название блюда"))
        self.lineEdit.setText(_translate("Add_database", "Впишите сюда..."))
