# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/change_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_database(object):
    def setupUi(self, Change_database):
        Change_database.setObjectName("Change_database")
        Change_database.resize(641, 620)
        self.centralwidget = QtWidgets.QWidget(Change_database)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 591, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(130, 430, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Times")
        self.save_button.setFont(font)
        self.save_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_button.setStyleSheet("border-radius: 50px;")
        self.save_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/save_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon)
        self.save_button.setIconSize(QtCore.QSize(70, 70))
        self.save_button.setFlat(True)
        self.save_button.setObjectName("save_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(400, 430, 71, 71))
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("border-radius: 50px;")
        self.exit_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon1)
        self.exit_button.setIconSize(QtCore.QSize(70, 70))
        self.exit_button.setFlat(True)
        self.exit_button.setObjectName("exit_button")
        Change_database.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Change_database)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        Change_database.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Change_database)
        self.statusbar.setObjectName("statusbar")
        Change_database.setStatusBar(self.statusbar)

        self.retranslateUi(Change_database)
        QtCore.QMetaObject.connectSlotsByName(Change_database)

    def retranslateUi(self, Change_database):
        _translate = QtCore.QCoreApplication.translate
        Change_database.setWindowTitle(_translate("Change_database", "Изменение данных"))
        self.save_button.setToolTip(_translate("Change_database", "<html><head/><body><p>Сохранить</p></body></html>"))
        self.exit_button.setToolTip(_translate("Change_database", "Выйти"))
