# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/change_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Change_database(object):
    def setupUi(self, Change_database):
        Change_database.setObjectName("Change_database")
        Change_database.resize(641, 620)
        self.centralwidget = QtWidgets.QWidget(Change_database)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 591, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 430, 591, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        Change_database.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Change_database)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        Change_database.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Change_database)
        self.statusbar.setObjectName("statusbar")
        Change_database.setStatusBar(self.statusbar)

        self.retranslateUi(Change_database)
        QtCore.QMetaObject.connectSlotsByName(Change_database)

    def retranslateUi(self, Change_database):
        _translate = QtCore.QCoreApplication.translate
        Change_database.setWindowTitle(_translate("Change_database", "Изменение данных"))
        self.save_button.setText(_translate("Change_database", "Сохранить"))
        self.pushButton_2.setText(_translate("Change_database", "Выйти"))
