# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/del_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Remove_database(object):
    def setupUi(self, Remove_database):
        Remove_database.setObjectName("Remove_database")
        Remove_database.resize(634, 620)
        Remove_database.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Remove_database)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 591, 391))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(30, 430, 71, 71))
        self.update_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_button.setStyleSheet("border-radius: 50px;")
        self.update_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/update_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_button.setIcon(icon)
        self.update_button.setIconSize(QtCore.QSize(70, 70))
        self.update_button.setFlat(False)
        self.update_button.setObjectName("update_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(280, 430, 71, 71))
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setStyleSheet("border-radius: 50px;")
        self.delete_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/delete_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_button.setIcon(icon1)
        self.delete_button.setIconSize(QtCore.QSize(70, 70))
        self.delete_button.setFlat(True)
        self.delete_button.setObjectName("delete_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(530, 430, 71, 71))
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("border-radius: 50px;")
        self.exit_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon2)
        self.exit_button.setIconSize(QtCore.QSize(70, 70))
        self.exit_button.setFlat(True)
        self.exit_button.setObjectName("exit_button")
        Remove_database.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Remove_database)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 634, 21))
        self.menubar.setObjectName("menubar")
        Remove_database.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Remove_database)
        self.statusbar.setObjectName("statusbar")
        Remove_database.setStatusBar(self.statusbar)

        self.retranslateUi(Remove_database)
        QtCore.QMetaObject.connectSlotsByName(Remove_database)

    def retranslateUi(self, Remove_database):
        _translate = QtCore.QCoreApplication.translate
        Remove_database.setWindowTitle(_translate("Remove_database", "Удаление данных"))
        self.update_button.setToolTip(_translate("Remove_database", "Обновить"))
        self.delete_button.setToolTip(_translate("Remove_database", "Удалить"))
        self.exit_button.setToolTip(_translate("Remove_database", "Выход"))
