# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/del_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Remove_database(object):
    def setupUi(self, Remove_database):
        Remove_database.setObjectName("Remove_database")
        Remove_database.resize(641, 620)
        self.centralwidget = QtWidgets.QWidget(Remove_database)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 591, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 430, 591, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.del_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.del_button.setObjectName("del_button")
        self.verticalLayout.addWidget(self.del_button)
        self.exit_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)
        Remove_database.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Remove_database)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName("menubar")
        Remove_database.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Remove_database)
        self.statusbar.setObjectName("statusbar")
        Remove_database.setStatusBar(self.statusbar)

        self.retranslateUi(Remove_database)
        QtCore.QMetaObject.connectSlotsByName(Remove_database)

    def retranslateUi(self, Remove_database):
        _translate = QtCore.QCoreApplication.translate
        Remove_database.setWindowTitle(_translate("Remove_database", "Удаление данных"))
        self.del_button.setText(_translate("Remove_database", "Удалить"))
        self.exit_button.setText(_translate("Remove_database", "Выйти"))
