# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/itog_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Itog(object):
    def setupUi(self, Itog):
        Itog.setObjectName("Itog")
        Itog.resize(459, 600)
        self.centralwidget = QtWidgets.QWidget(Itog)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 20, 381, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 420, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setTabletTracking(False)
        self.label.setAcceptDrops(False)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(340, 470, 71, 71))
        self.exit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_button.setStyleSheet("border-radius: 50px;")
        self.exit_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon)
        self.exit_button.setIconSize(QtCore.QSize(70, 70))
        self.exit_button.setObjectName("exit_button")
        Itog.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Itog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        Itog.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Itog)
        self.statusbar.setObjectName("statusbar")
        Itog.setStatusBar(self.statusbar)

        self.retranslateUi(Itog)
        QtCore.QMetaObject.connectSlotsByName(Itog)

    def retranslateUi(self, Itog):
        _translate = QtCore.QCoreApplication.translate
        Itog.setWindowTitle(_translate("Itog", "Список покупок"))
        self.label.setText(_translate("Itog", "Ваш список покупок сформирован и записан в файл shopping_list.txt"))
